### ISSUE TITLE
Incorrect line-endings?

### ISSUE THREAD

**Issue by Penggeor** [Rettend/eemoji#11]
Thank for your excellent product. I encountered an error:
```
git commit -m "feat: add typescript"
: command not foundcommit-msg: line 4: 
.git/hooks/prepare-commit-msg: line 7: syntax error near unexpected token `elif'
'git/hooks/prepare-commit-msg: line 7: `elif [ -f "$NODE_PATH/eemoji/bin/eemoji.mjs" ]; then
```
I ask Copilot that the problem maybe is line-endings:
<img width="361" alt="image" src="https://github.com/Rettend/eemoji/assets/68799055/fce923d5-3ce7-4232-8186-db0620c3cfd1">

My environment:

<img width="316" alt="image" src="https://github.com/Rettend/eemoji/assets/68799055/692bb066-2f63-46f3-bbe3-603b4938b174">

**Comment by Rettend** [comment]
Hi, thanks for pointing this out.
You are right, I thought git converted my files to LF but apparently it didn't.

Can you upgrade the package to `v1.1.5` and try it again? :shipit:
